FROM amazoncorretto:17

MAINTAINER julianmeneses

COPY target/proyectoSpringBoot-0.0.1-SNAPSHOT.jar proyectoSpringBoot-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/proyectoSpringBoot-0.0.1-SNAPSHOT.jar"]